#include "dxr_renderer.hpp"
#include "math.hpp"
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <algorithm>
#include <cmath>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

namespace dense {
namespace {
template<class T>void release(T*&p){if(p){p->Release();p=nullptr;}}
constexpr UINT64 alignUp(UINT64 value,UINT64 alignment){return(value+alignment-1)&~(alignment-1);}
D3D12_HEAP_PROPERTIES heap(D3D12_HEAP_TYPE type){D3D12_HEAP_PROPERTIES h{};h.Type=type;h.CPUPageProperty=D3D12_CPU_PAGE_PROPERTY_UNKNOWN;h.MemoryPoolPreference=D3D12_MEMORY_POOL_UNKNOWN;h.CreationNodeMask=1;h.VisibleNodeMask=1;return h;}
D3D12_RESOURCE_DESC bufferDesc(UINT64 bytes,D3D12_RESOURCE_FLAGS flags=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=bytes;d.Height=1;d.DepthOrArraySize=1;d.MipLevels=1;d.Format=DXGI_FORMAT_UNKNOWN;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=flags;return d;}
D3D12_RESOURCE_BARRIER transition(ID3D12Resource*r,D3D12_RESOURCE_STATES before,D3D12_RESOURCE_STATES after){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition.pResource=r;b.Transition.StateBefore=before;b.Transition.StateAfter=after;b.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;return b;}
}

struct DxrRenderer::Impl{
    HWND window{};int width=1,height=1;std::wstring lastError;bool initialized=false;UINT frameIndex=0;float lastYaw=99,lastPitch=99,lastDistance=0,lastSun=99;
    IDXGIFactory6*factory{};IDXGISwapChain3*swap{};ID3D12Device5*device{};ID3D12CommandQueue*queue{};ID3D12CommandAllocator*allocator{};ID3D12GraphicsCommandList4*list{};
    ID3D12Fence*fence{};HANDLE fenceEvent{};UINT64 fenceValue{};ID3D12DescriptorHeap*rtvHeap{};ID3D12DescriptorHeap*gpuHeap{};UINT rtvSize{};ID3D12Resource*backBuffers[2]{};
    ID3D12RootSignature*root{};ID3D12StateObject*state{};ID3D12StateObjectProperties*stateProps{};
    ID3D12Resource*output{};ID3D12Resource*accumulation{};ID3D12Resource*cameraBuffer{};void*cameraMapped{};
    ID3D12Resource*vertexBuffer{};ID3D12Resource*indexBuffer{};ID3D12Resource*blas{};ID3D12Resource*tlas{};ID3D12Resource*blasScratch{};ID3D12Resource*tlasScratch{};ID3D12Resource*instanceBuffer{};
    ID3D12Resource*raygenTable{};ID3D12Resource*missTable{};ID3D12Resource*hitTable{};UINT vertexCount{},indexCount{};

    ~Impl(){wait();if(cameraBuffer&&cameraMapped)cameraBuffer->Unmap(0,nullptr);release(hitTable);release(missTable);release(raygenTable);release(instanceBuffer);release(tlasScratch);release(blasScratch);release(tlas);release(blas);release(indexBuffer);release(vertexBuffer);release(cameraBuffer);release(accumulation);release(output);release(stateProps);release(state);release(root);for(auto&b:backBuffers)release(b);release(gpuHeap);release(rtvHeap);release(list);release(allocator);release(fence);release(queue);release(swap);release(device);release(factory);if(fenceEvent)CloseHandle(fenceEvent);}
    bool fail(HRESULT hr,const wchar_t*message){wchar_t text[320];wsprintfW(text,L"%s (HRESULT 0x%08X)",message,static_cast<unsigned>(hr));lastError=text;return false;}
    void wait(){if(!queue||!fence)return;const UINT64 value=++fenceValue;if(SUCCEEDED(queue->Signal(fence,value))&&fence->GetCompletedValue()<value){fence->SetEventOnCompletion(value,fenceEvent);WaitForSingleObject(fenceEvent,INFINITE);}}
    bool begin(){wait();if(FAILED(allocator->Reset()))return false;if(FAILED(list->Reset(allocator,nullptr)))return false;return true;}
    bool execute(){if(FAILED(list->Close()))return false;ID3D12CommandList*commands[]={list};queue->ExecuteCommandLists(1,commands);wait();return true;}
    ID3D12Resource*makeBuffer(UINT64 bytes,D3D12_HEAP_TYPE type,D3D12_RESOURCE_STATES state,D3D12_RESOURCE_FLAGS flags=D3D12_RESOURCE_FLAG_NONE){ID3D12Resource*r{};auto h=heap(type);auto d=bufferDesc(std::max<UINT64>(bytes,256),flags);if(FAILED(device->CreateCommittedResource(&h,D3D12_HEAP_FLAG_NONE,&d,state,nullptr,__uuidof(ID3D12Resource),reinterpret_cast<void**>(&r))))return nullptr;return r;}
    template<class T>ID3D12Resource*upload(const std::vector<T>&data){ID3D12Resource*r=makeBuffer(data.size()*sizeof(T),D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);if(!r)return nullptr;void*mapped{};if(FAILED(r->Map(0,nullptr,&mapped))){release(r);return nullptr;}std::memcpy(mapped,data.data(),data.size()*sizeof(T));r->Unmap(0,nullptr);return r;}
    bool createBackBuffers(){D3D12_CPU_DESCRIPTOR_HANDLE handle=rtvHeap->GetCPUDescriptorHandleForHeapStart();for(UINT n=0;n<2;++n){HRESULT hr=swap->GetBuffer(n,__uuidof(ID3D12Resource),reinterpret_cast<void**>(&backBuffers[n]));if(FAILED(hr))return fail(hr,L"DXR swap-chain buffer creation failed");device->CreateRenderTargetView(backBuffers[n],nullptr,handle);handle.ptr+=rtvSize;}return true;}
    bool createOutputs(){release(output);release(accumulation);D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;d.Width=width;d.Height=height;d.DepthOrArraySize=1;d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_UNKNOWN;d.Flags=D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;auto h=heap(D3D12_HEAP_TYPE_DEFAULT);
        d.Format=DXGI_FORMAT_R8G8B8A8_UNORM;HRESULT hr=device->CreateCommittedResource(&h,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,__uuidof(ID3D12Resource),reinterpret_cast<void**>(&output));if(FAILED(hr))return fail(hr,L"DXR output texture creation failed");
        d.Format=DXGI_FORMAT_R32G32B32A32_FLOAT;hr=device->CreateCommittedResource(&h,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,__uuidof(ID3D12Resource),reinterpret_cast<void**>(&accumulation));if(FAILED(hr))return fail(hr,L"DXR accumulation texture creation failed");
        auto cpu=gpuHeap->GetCPUDescriptorHandleForHeapStart();D3D12_UNORDERED_ACCESS_VIEW_DESC u{};u.ViewDimension=D3D12_UAV_DIMENSION_TEXTURE2D;u.Format=DXGI_FORMAT_R8G8B8A8_UNORM;device->CreateUnorderedAccessView(output,nullptr,&u,cpu);cpu.ptr+=device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);u.Format=DXGI_FORMAT_R32G32B32A32_FLOAT;device->CreateUnorderedAccessView(accumulation,nullptr,&u,cpu);frameIndex=0;return true;}
    std::vector<char>loadDxil(){wchar_t exe[MAX_PATH]{};GetModuleFileNameW(nullptr,exe,MAX_PATH);auto path=std::filesystem::path(exe).parent_path().parent_path()/L"shaders"/L"raytracing.dxil";std::ifstream stream(path,std::ios::binary|std::ios::ate);if(!stream)return{};const auto size=stream.tellg();stream.seekg(0);std::vector<char>data(static_cast<size_t>(size));stream.read(data.data(),size);return data;}
    bool createPipeline(){D3D12_DESCRIPTOR_RANGE range{};range.RangeType=D3D12_DESCRIPTOR_RANGE_TYPE_UAV;range.NumDescriptors=2;range.BaseShaderRegister=0;range.OffsetInDescriptorsFromTableStart=0;
        D3D12_ROOT_PARAMETER params[5]{};params[0].ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;params[0].DescriptorTable.NumDescriptorRanges=1;params[0].DescriptorTable.pDescriptorRanges=&range;for(int p=1;p<=3;++p){params[p].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;params[p].Descriptor.ShaderRegister=static_cast<UINT>(p-1);}params[4].ParameterType=D3D12_ROOT_PARAMETER_TYPE_CBV;params[4].Descriptor.ShaderRegister=0;
        D3D12_ROOT_SIGNATURE_DESC rs{};rs.NumParameters=5;rs.pParameters=params;ID3DBlob*blob{},*errors{};HRESULT hr=D3D12SerializeRootSignature(&rs,D3D_ROOT_SIGNATURE_VERSION_1,&blob,&errors);if(FAILED(hr)){release(errors);return fail(hr,L"DXR root-signature serialization failed");}hr=device->CreateRootSignature(0,blob->GetBufferPointer(),blob->GetBufferSize(),__uuidof(ID3D12RootSignature),reinterpret_cast<void**>(&root));release(blob);release(errors);if(FAILED(hr))return fail(hr,L"DXR root-signature creation failed");
        auto dxil=loadDxil();if(dxil.empty()){lastError=L"Compiled raytracing.dxil was not found beside the build output.";return false;}
        const wchar_t*exports[]={L"RayGen",L"RadianceMiss",L"VisibilityMiss",L"RadianceHit",L"VisibilityHit"};D3D12_EXPORT_DESC exportDescs[5]{};for(int n=0;n<5;++n)exportDescs[n].Name=exports[n];D3D12_DXIL_LIBRARY_DESC library{};library.DXILLibrary={dxil.data(),dxil.size()};library.NumExports=5;library.pExports=exportDescs;
        D3D12_HIT_GROUP_DESC hit0{};hit0.HitGroupExport=L"RadianceHitGroup";hit0.ClosestHitShaderImport=L"RadianceHit";hit0.Type=D3D12_HIT_GROUP_TYPE_TRIANGLES;D3D12_HIT_GROUP_DESC hit1{};hit1.HitGroupExport=L"VisibilityHitGroup";hit1.ClosestHitShaderImport=L"VisibilityHit";hit1.Type=D3D12_HIT_GROUP_TYPE_TRIANGLES;
        D3D12_RAYTRACING_SHADER_CONFIG shaderConfig{16,8};D3D12_GLOBAL_ROOT_SIGNATURE global{root};D3D12_RAYTRACING_PIPELINE_CONFIG pipeline{3};D3D12_STATE_SUBOBJECT subs[7]{};subs[0]={D3D12_STATE_SUBOBJECT_TYPE_DXIL_LIBRARY,&library};subs[1]={D3D12_STATE_SUBOBJECT_TYPE_HIT_GROUP,&hit0};subs[2]={D3D12_STATE_SUBOBJECT_TYPE_HIT_GROUP,&hit1};subs[3]={D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_SHADER_CONFIG,&shaderConfig};const wchar_t*associations[]={L"RayGen",L"RadianceMiss",L"VisibilityMiss",L"RadianceHitGroup",L"VisibilityHitGroup"};D3D12_SUBOBJECT_TO_EXPORTS_ASSOCIATION association{&subs[3],5,associations};subs[4]={D3D12_STATE_SUBOBJECT_TYPE_SUBOBJECT_TO_EXPORTS_ASSOCIATION,&association};subs[5]={D3D12_STATE_SUBOBJECT_TYPE_GLOBAL_ROOT_SIGNATURE,&global};subs[6]={D3D12_STATE_SUBOBJECT_TYPE_RAYTRACING_PIPELINE_CONFIG,&pipeline};D3D12_STATE_OBJECT_DESC desc{D3D12_STATE_OBJECT_TYPE_RAYTRACING_PIPELINE,7,subs};hr=device->CreateStateObject(&desc,__uuidof(ID3D12StateObject),reinterpret_cast<void**>(&state));if(FAILED(hr))return fail(hr,L"DXR state-object creation failed");hr=state->QueryInterface(__uuidof(ID3D12StateObjectProperties),reinterpret_cast<void**>(&stateProps));if(FAILED(hr))return fail(hr,L"DXR state-object properties unavailable");return createShaderTables();}
    ID3D12Resource*shaderTable(const std::vector<const void*>&ids){const UINT stride=D3D12_SHADER_IDENTIFIER_SIZE_IN_BYTES;ID3D12Resource*r=makeBuffer(alignUp(ids.size()*stride,D3D12_RAYTRACING_SHADER_TABLE_BYTE_ALIGNMENT),D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);if(!r)return nullptr;void*m{};r->Map(0,nullptr,&m);for(size_t i=0;i<ids.size();++i)std::memcpy(static_cast<char*>(m)+i*stride,ids[i],stride);r->Unmap(0,nullptr);return r;}
    bool createShaderTables(){const void*rg=stateProps->GetShaderIdentifier(L"RayGen"),*rm=stateProps->GetShaderIdentifier(L"RadianceMiss"),*vm=stateProps->GetShaderIdentifier(L"VisibilityMiss"),*rh=stateProps->GetShaderIdentifier(L"RadianceHitGroup"),*vh=stateProps->GetShaderIdentifier(L"VisibilityHitGroup");if(!rg||!rm||!vm||!rh||!vh){lastError=L"DXR shader identifier lookup failed.";return false;}raygenTable=shaderTable({rg});missTable=shaderTable({rm,vm});hitTable=shaderTable({rh,vh});return raygenTable&&missTable&&hitTable;}
    bool buildAcceleration(const TreeMesh&tree){wait();release(instanceBuffer);release(tlasScratch);release(blasScratch);release(tlas);release(blas);release(indexBuffer);release(vertexBuffer);
        std::vector<MeshVertex>vertices=tree.branchVertices;std::vector<uint32_t>indices=tree.branchIndices;const uint32_t leafBase=static_cast<uint32_t>(vertices.size());vertices.insert(vertices.end(),tree.leafVertices.begin(),tree.leafVertices.end());indices.reserve(indices.size()+tree.leafIndices.size()+6);for(uint32_t index:tree.leafIndices)indices.push_back(leafBase+index);const uint32_t groundBase=static_cast<uint32_t>(vertices.size());const uint32_t ground=0xff365139u;vertices.insert(vertices.end(),{{{-20,0,-20},{0,1,0},ground,2},{{-20,0,20},{0,1,0},ground,2},{{20,0,20},{0,1,0},ground,2},{{20,0,-20},{0,1,0},ground,2}});indices.insert(indices.end(),{groundBase,groundBase+1,groundBase+2,groundBase,groundBase+2,groundBase+3});vertexCount=static_cast<UINT>(vertices.size());indexCount=static_cast<UINT>(indices.size());vertexBuffer=upload(vertices);indexBuffer=upload(indices);if(!vertexBuffer||!indexBuffer){lastError=L"DXR geometry upload failed.";return false;}
        D3D12_RAYTRACING_GEOMETRY_DESC geometry{};geometry.Type=D3D12_RAYTRACING_GEOMETRY_TYPE_TRIANGLES;geometry.Flags=D3D12_RAYTRACING_GEOMETRY_FLAG_OPAQUE;geometry.Triangles.VertexBuffer.StartAddress=vertexBuffer->GetGPUVirtualAddress();geometry.Triangles.VertexBuffer.StrideInBytes=sizeof(MeshVertex);geometry.Triangles.VertexCount=vertexCount;geometry.Triangles.VertexFormat=DXGI_FORMAT_R32G32B32_FLOAT;geometry.Triangles.IndexBuffer=indexBuffer->GetGPUVirtualAddress();geometry.Triangles.IndexCount=indexCount;geometry.Triangles.IndexFormat=DXGI_FORMAT_R32_UINT;
        D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INPUTS input{};input.Type=D3D12_RAYTRACING_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL;input.Flags=D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_PREFER_FAST_TRACE;input.NumDescs=1;input.pGeometryDescs=&geometry;D3D12_RAYTRACING_ACCELERATION_STRUCTURE_PREBUILD_INFO info{};device->GetRaytracingAccelerationStructurePrebuildInfo(&input,&info);blasScratch=makeBuffer(info.ScratchDataSizeInBytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);blas=makeBuffer(info.ResultDataMaxSizeInBytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);if(!blasScratch||!blas)return false;
        if(!begin())return false;D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_DESC build{};build.Inputs=input;build.ScratchAccelerationStructureData=blasScratch->GetGPUVirtualAddress();build.DestAccelerationStructureData=blas->GetGPUVirtualAddress();list->BuildRaytracingAccelerationStructure(&build,0,nullptr);D3D12_RESOURCE_BARRIER uav{};uav.Type=D3D12_RESOURCE_BARRIER_TYPE_UAV;uav.UAV.pResource=blas;list->ResourceBarrier(1,&uav);if(!execute())return false;
        D3D12_RAYTRACING_INSTANCE_DESC instance{};instance.Transform[0][0]=instance.Transform[1][1]=instance.Transform[2][2]=1;instance.InstanceMask=0xff;instance.AccelerationStructure=blas->GetGPUVirtualAddress();std::vector<D3D12_RAYTRACING_INSTANCE_DESC>instances{instance};instanceBuffer=upload(instances);D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_INPUTS ti{};ti.Type=D3D12_RAYTRACING_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL;ti.Flags=D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_PREFER_FAST_TRACE;ti.NumDescs=1;ti.DescsLayout=D3D12_ELEMENTS_LAYOUT_ARRAY;ti.InstanceDescs=instanceBuffer->GetGPUVirtualAddress();device->GetRaytracingAccelerationStructurePrebuildInfo(&ti,&info);tlasScratch=makeBuffer(info.ScratchDataSizeInBytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);tlas=makeBuffer(info.ResultDataMaxSizeInBytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);if(!tlasScratch||!tlas)return false;if(!begin())return false;build={};build.Inputs=ti;build.ScratchAccelerationStructureData=tlasScratch->GetGPUVirtualAddress();build.DestAccelerationStructureData=tlas->GetGPUVirtualAddress();list->BuildRaytracingAccelerationStructure(&build,0,nullptr);uav.UAV.pResource=tlas;list->ResourceBarrier(1,&uav);if(!execute())return false;frameIndex=0;return true;}
};

DxrRenderer::DxrRenderer():impl_(std::make_unique<Impl>()){}DxrRenderer::~DxrRenderer()=default;
bool DxrRenderer::initialize(HWND window,int width,int height){auto&i=*impl_;i.window=window;i.width=std::max(1,width);i.height=std::max(1,height);HRESULT hr=CreateDXGIFactory1(__uuidof(IDXGIFactory6),reinterpret_cast<void**>(&i.factory));if(FAILED(hr))return i.fail(hr,L"DXGI factory creation failed");IDXGIAdapter1*adapter{};for(UINT n=0;i.factory->EnumAdapterByGpuPreference(n,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,__uuidof(IDXGIAdapter1),reinterpret_cast<void**>(&adapter))!=DXGI_ERROR_NOT_FOUND;++n){DXGI_ADAPTER_DESC1 d{};adapter->GetDesc1(&d);if(!(d.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&SUCCEEDED(D3D12CreateDevice(adapter,D3D_FEATURE_LEVEL_12_1,__uuidof(ID3D12Device5),reinterpret_cast<void**>(&i.device))))break;release(adapter);}release(adapter);if(!i.device){i.lastError=L"No DXR-capable DirectX 12 device was found.";return false;}D3D12_FEATURE_DATA_D3D12_OPTIONS5 options{};if(FAILED(i.device->CheckFeatureSupport(D3D12_FEATURE_D3D12_OPTIONS5,&options,sizeof(options)))||options.RaytracingTier==D3D12_RAYTRACING_TIER_NOT_SUPPORTED){i.lastError=L"The selected GPU does not expose DXR.";return false;}
    D3D12_COMMAND_QUEUE_DESC q{};q.Type=D3D12_COMMAND_LIST_TYPE_DIRECT;hr=i.device->CreateCommandQueue(&q,__uuidof(ID3D12CommandQueue),reinterpret_cast<void**>(&i.queue));if(FAILED(hr))return i.fail(hr,L"DXR command queue creation failed");hr=i.device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,__uuidof(ID3D12CommandAllocator),reinterpret_cast<void**>(&i.allocator));if(FAILED(hr))return i.fail(hr,L"DXR command allocator creation failed");hr=i.device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,i.allocator,nullptr,__uuidof(ID3D12GraphicsCommandList4),reinterpret_cast<void**>(&i.list));if(FAILED(hr))return i.fail(hr,L"DXR command-list creation failed");i.list->Close();
    DXGI_SWAP_CHAIN_DESC1 sd{};sd.Width=i.width;sd.Height=i.height;sd.Format=DXGI_FORMAT_R8G8B8A8_UNORM;sd.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;sd.BufferCount=2;sd.SampleDesc.Count=1;sd.SwapEffect=DXGI_SWAP_EFFECT_FLIP_DISCARD;IDXGISwapChain1*base{};hr=i.factory->CreateSwapChainForHwnd(i.queue,window,&sd,nullptr,nullptr,&base);if(FAILED(hr))return i.fail(hr,L"DXR swap chain creation failed");hr=base->QueryInterface(__uuidof(IDXGISwapChain3),reinterpret_cast<void**>(&i.swap));release(base);if(FAILED(hr))return i.fail(hr,L"DXR swap-chain interface unavailable");
    D3D12_DESCRIPTOR_HEAP_DESC rh{};rh.Type=D3D12_DESCRIPTOR_HEAP_TYPE_RTV;rh.NumDescriptors=2;i.device->CreateDescriptorHeap(&rh,__uuidof(ID3D12DescriptorHeap),reinterpret_cast<void**>(&i.rtvHeap));i.rtvSize=i.device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_RTV);D3D12_DESCRIPTOR_HEAP_DESC gh{};gh.Type=D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;gh.NumDescriptors=2;gh.Flags=D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;i.device->CreateDescriptorHeap(&gh,__uuidof(ID3D12DescriptorHeap),reinterpret_cast<void**>(&i.gpuHeap));i.device->CreateFence(0,D3D12_FENCE_FLAG_NONE,__uuidof(ID3D12Fence),reinterpret_cast<void**>(&i.fence));i.fenceEvent=CreateEventW(nullptr,FALSE,FALSE,nullptr);if(!i.createBackBuffers()||!i.createOutputs()||!i.createPipeline())return false;i.cameraBuffer=i.makeBuffer(256,D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);if(!i.cameraBuffer||FAILED(i.cameraBuffer->Map(0,nullptr,&i.cameraMapped)))return false;i.initialized=true;return true;}
void DxrRenderer::resize(int width,int height){auto&i=*impl_;if(!i.initialized||width<=0||height<=0)return;i.wait();i.width=width;i.height=height;for(auto&b:i.backBuffers)release(b);if(SUCCEEDED(i.swap->ResizeBuffers(0,width,height,DXGI_FORMAT_UNKNOWN,0))){i.createBackBuffers();i.createOutputs();}}
void DxrRenderer::setTree(const TreeMesh&tree){if(impl_->initialized&&!impl_->buildAcceleration(tree))MessageBoxW(impl_->window,impl_->lastError.c_str(),L"Dense Trees DXR geometry error",MB_ICONERROR);}
void DxrRenderer::render(float yaw,float pitch,float distance,float sunAzimuth){auto&i=*impl_;if(!i.initialized||!i.tlas)return;if(std::abs(yaw-i.lastYaw)>.0001f||std::abs(pitch-i.lastPitch)>.0001f||std::abs(distance-i.lastDistance)>.0001f||std::abs(sunAzimuth-i.lastSun)>.0001f){i.frameIndex=0;i.lastYaw=yaw;i.lastPitch=pitch;i.lastDistance=distance;i.lastSun=sunAzimuth;}
    const Vec3 target{0,4.1f,0},eye=target+Vec3{std::sin(yaw)*std::cos(pitch)*distance,std::sin(pitch)*distance,-std::cos(yaw)*std::cos(pitch)*distance};const Vec3 forward=normalize(target-eye),right=normalize(cross({0,1,0},forward)),up=cross(forward,right);
    struct Camera{float eye[3],tanHalf;float forward[3],aspect;float right[3];UINT frame;float up[3];UINT maxFrames;float sun[3],exposure;UINT resolution[2],padding[2];}c{{eye.x,eye.y,eye.z},std::tan(52*pi/360),{forward.x,forward.y,forward.z},static_cast<float>(i.width)/i.height,{right.x,right.y,right.z},i.frameIndex,{up.x,up.y,up.z},1024,{-std::sin(sunAzimuth),-1.35f,-std::cos(sunAzimuth)},1.12f,{static_cast<UINT>(i.width),static_cast<UINT>(i.height)},{0,0}};std::memcpy(i.cameraMapped,&c,sizeof(c));if(!i.begin())return;
    ID3D12DescriptorHeap*heaps[]={i.gpuHeap};i.list->SetDescriptorHeaps(1,heaps);i.list->SetComputeRootSignature(i.root);i.list->SetPipelineState1(i.state);i.list->SetComputeRootDescriptorTable(0,i.gpuHeap->GetGPUDescriptorHandleForHeapStart());i.list->SetComputeRootShaderResourceView(1,i.tlas->GetGPUVirtualAddress());i.list->SetComputeRootShaderResourceView(2,i.vertexBuffer->GetGPUVirtualAddress());i.list->SetComputeRootShaderResourceView(3,i.indexBuffer->GetGPUVirtualAddress());i.list->SetComputeRootConstantBufferView(4,i.cameraBuffer->GetGPUVirtualAddress());
    D3D12_DISPATCH_RAYS_DESC rays{};rays.RayGenerationShaderRecord={i.raygenTable->GetGPUVirtualAddress(),D3D12_SHADER_IDENTIFIER_SIZE_IN_BYTES};rays.MissShaderTable={i.missTable->GetGPUVirtualAddress(),D3D12_SHADER_IDENTIFIER_SIZE_IN_BYTES*2,D3D12_SHADER_IDENTIFIER_SIZE_IN_BYTES};rays.HitGroupTable={i.hitTable->GetGPUVirtualAddress(),D3D12_SHADER_IDENTIFIER_SIZE_IN_BYTES*2,D3D12_SHADER_IDENTIFIER_SIZE_IN_BYTES};rays.Width=i.width;rays.Height=i.height;rays.Depth=1;i.list->DispatchRays(&rays);const UINT back=i.swap->GetCurrentBackBufferIndex();D3D12_RESOURCE_BARRIER barriers[]={transition(i.output,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_COPY_SOURCE),transition(i.backBuffers[back],D3D12_RESOURCE_STATE_PRESENT,D3D12_RESOURCE_STATE_COPY_DEST)};i.list->ResourceBarrier(2,barriers);i.list->CopyResource(i.backBuffers[back],i.output);barriers[0]=transition(i.output,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);barriers[1]=transition(i.backBuffers[back],D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_PRESENT);i.list->ResourceBarrier(2,barriers);if(i.execute()){i.swap->Present(1,0);i.frameIndex=std::min<UINT>(i.frameIndex+1,1023);}}
const wchar_t*DxrRenderer::error()const{return impl_->lastError.c_str();}bool DxrRenderer::ready()const{return impl_->initialized;}
}
